version: '3.8'

name: wheelz
services:
  postgres:
    container_name: wheelz
    image: 'postgres:15'
    environment:
      POSTGRES_DB: wheelz_db
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
